BSD closes #122: Fixed address issue on Contract Vehicle
Bixal/bixal-site-drupal pull request #131
Opened 2024-04-12 14:08 UTC by buddy-harlow

- _Created_ address paragraph with fields for name & title, email, phone number
- _Created_ address paragraph template to format match what was in storybook
- **Revised** contract vehicle fields to utilize the new address paragraph
- **Revised** contract vehicle template to display each field individually in order to work in the key points of contact text
- **Revised** default content to fit new field for addresses
- Closes #122

2024-04-16 16:58 UTC, mpbixal requested changes

2024-04-19 17:35 UTC, buddy-harlow commented
@mpbixal Alrighty, added the ability to add a linebreak to that field, fixed the hyperlinks, and I believe I removed a bunch of the extra wrappers.

2024-04-23 18:41 UTC, mpbixal commented
> @mpbixal Alrighty, added the ability to add a linebreak to that field, fixed the hyperlinks, and I believe I removed a bunch of the extra wrappers.

Thanks Buddy! I've reviewed and created this branch feature/BSD-122-contact-information-m. Can you please compare and let me know if I haven't broke anything.

2024-05-02 21:22 UTC, mpbixal approved these changes

2024-05-02 21:26 UTC, merged